# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_direction', models.FloatField()),
                ('y_direction', models.FloatField()),
            ],
        ),
    ]
